### ISSUE TITLE
Unexpected tmpfail with Extlookup on

### ISSUE THREAD

**Issue by falon** [whyscream/dspam-milter#37]
If I configure DSPAM with
`ExtLookup on`
I can receive a recipient response different from which I sent in RCPT:

```
MAIL FROM:<kkkkkk@dspam> DSPAMPROCESSMODE="--process --deliver=summary"
250 2.1.0 OK
RCPT TO:<useralias@example.com>
250 2.1.5 OK
data
354 Enter mail, end with "." on a line by itself
From: me
To: you

Hello
.
250 2.6.0 <user@example.com> Message accepted for delivery: INNOCENT

```
This is the effect:
```
2017-09-05T12:36:02.574484+02:00 postfix dspam.milter[7270]: ERROR <787> An error ocurred while talking to DSPAM: Message was accepted for unknown recipient user@example.com
2017-09-05T12:36:02.574558+02:00 postfix postfix/cleanup[8971]: 3xmjmd1jknzFpjJ: milter-reject: END-OF-MESSAGE from client.example.com[10.10.10.10]: 4.7.1 Service unavailable - try again later; from=<me@example.com> to=<useralias@example.com> proto=ESMTP helo=<client.example.com>
```

**Comment by whyscream** [comment]
Thanks for reporting!
This seems like a bug. Currently, the recipients sent using the `RCPT TO` command are used to check whether we received results for all recipients from DSPAM already. Probably this is too strict and we could change it to just check the count of recipients and responses.

I could look into this in a few days, when I'm back from my holidays.

**Comment by falon** [comment]
I commented line 249 of client.py and the following "else".

Unfortunately this milter seems to have some problems if I use dspam only to add headers result (not for reject). For instance, I don't want this:
```
# With multiple recipients, if different verdicts were returned, always
#   use the 'lowest' verdict as final, so mail is not lost unexpected.
```

Have a nice holidays!
Bye

**Comment by whyscream** [comment]
https://github.com/whyscream/dspam-milter/pull/38 This PR should solve your issue. an you please check?

**Comment by falon** [comment]
It works!
Thank you very much
